const ftp = require("basic-ftp");
const path = require("path");

async function deploy() {
    const client = new ftp.Client()
    client.ftp.verbose = true
    try {
        await client.access({
            host: "ftp.web22f49.kinghost.net",
            user: "fortunatoagricola",
            password: "Admfortunato36",
            secure: false
        })
        console.log("Connected to FTP.");

        console.log("Building Backend locally (Self-Contained win-x86)...");
        const { execSync } = require("child_process");
        const backendPath = path.resolve(__dirname, "../BackEnd/FortunatoAgricola.API");
        execSync("dotnet publish -c Release -r win-x86 --self-contained true -p:PublishSingleFile=false -p:PublishTrimmed=false -o publish-x86", {
            cwd: backendPath,
            stdio: "inherit"
        });
        console.log("Build successfully completed!");

        console.log("Uploading Backend to /www/api...");
        await client.ensureDir("/www/api");
        await client.cd("/www/api");

        // Clear old backend files to avoid garbage
        console.log("Clearing /www/api...");
        await client.clearWorkingDir();

        console.log("Uploading from publish-x86...");
        const publishFolder = path.resolve(__dirname, "../BackEnd/FortunatoAgricola.API/publish-x86");
        // We delete the local web.config from publish folder just to be sure it doesn't try to overwrite, 
        // with the wrong configuration generated by dotnet
        const fs = require('fs');
        if (fs.existsSync(path.join(publishFolder, 'web.config'))) {
            fs.unlinkSync(path.join(publishFolder, 'web.config'));
        }

        await client.uploadFromDir(publishFolder);

        console.log("Uploading predefined root webconfig.txt to web.config...");
        await client.uploadFrom(path.resolve(__dirname, "../webconfig.txt"), "web.config");

        console.log("✅ Backend uploaded successfully.");

        console.log("Building Frontend locally...");
        execSync("npm run build", {
            cwd: __dirname,
            stdio: "inherit"
        });
        console.log("Frontend build successfully completed!");

        console.log("Uploading Frontend to /www...");
        await client.cd("/");
        await client.ensureDir("/www");
        await client.cd("/www");
        await client.uploadFromDir(path.resolve(__dirname, "./dist/front-end-app/browser"));

        console.log("Uploading Frontend Routing web.config to /www...");
        await client.uploadFrom(path.resolve(__dirname, "../webconfig-frontend.txt"), "web.config");

        console.log("✅ Frontend uploaded successfully.");
    }
    catch (err) {
        console.log("❌ Error:", err)
    }
    client.close()
}

deploy();
